### ISSUE TITLE
Material design codelab not in English.

### ISSUE THREAD

**Issue by khayapro** [googlecodelabs/android-design-library#10]
On the following link:
<a href="https://codelabs.developers.google.com/codelabs/material-design-style-ru/index.html?index=..%2F..%2Fio2016#0">Material Design Codelabs</a>

**Comment by keyboardsurfer** [comment]
This is working as intended.
You've found the Russian version of the codelab.
An [English version](https://codelabs.developers.google.com/codelabs/material-design-style/index.html#0) is available as well.

**Comment by khayapro** [comment]
Thank you @keyboardsurfer , my bad.
