### ISSUE TITLE
FAB issue

### ISSUE THREAD

**Issue by amouly** [googlecodelabs/android-design-library#4]
The FAB button on example 5 hasn't got proper elevation or shadow.

**Comment by amouly** [comment]
Well, actually the shadow it's ok because inherits from Material Design lib. But I've found an issue when tapping the FAB button multiple times, the snackbar it's over the FAB.

**Comment by ghost** [comment]
@amouly solved adding behavior for FAB. [Example](https://github.com/ggajews/coordinatorlayoutwithfabdemo/blob/master/app/src/main/java/com/getbase/coordinatorlayoutdemo/FloatingActionButtonBehavior.java)

**Comment by taquo** [comment]
This issue was solved after updating to support library version.
