### ISSUE TITLE
Line Missing in Online Tutorial Version, in 5 Style Each View, Under #14

### ISSUE THREAD

**Issue by ramonagraham** [googlecodelabs/android-design-library#9]
On the webpage tutorial, in the section #5 Style Each View and Add a Recycler View
Then under #14, in the TileContentFragment onCreateView class, there are two recyclerView statements when there should be three as listed in GitHub

public View onCreateView(LayoutInflater inflater, ViewGroup container,
       Bundle savedInstanceState) {
       RecyclerView recyclerView = (RecyclerView) inflater.inflate(
                R.layout.recycler_view, container, false);
        ContentAdapter adapter = new ContentAdapter();
        recyclerView.setAdapter(adapter);
        recyclerView.setHasFixedSize(true);      

```
    // this is the 3rd recyclerView.set statement added from Github that is missing in the online tutorial
    recyclerView.setLayoutManager(new LinearLayoutManager(getActivity()));
```

**Comment by taquo** [comment]
Thank you for reporting issues, this should be solved after updating our codelab document!
